---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: ephemeral
---
apiVersion: v1
kind: Pod
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
spec:
  containers:
  - name: ${NAME}
    imagePullPolicy: Always
    image: "${CONTAINER_IMAGE}:${VERSION}"
    resources:
      requests:
        memory: 1536Mi
        cpu: 1500m
    ports:
    - containerPort: 30333
      name: p2p
    - containerPort: 9933
      name: http-rpc
    args:
      - --base-path
      - /polkadot
      - --name
      - ${NAME}
      - --rpc-external
      - --log
      - sync=trace
    volumeMounts:
    - name: polkasyncdir
      mountPath: /polkadot
    readinessProbe:
      httpGet:
        path: /health
        port: http-rpc
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: http-rpc
      initialDelaySeconds: 10
      periodSeconds: 10
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  volumes:
    - name: polkasyncdir
      persistentVolumeClaim:
        claimName: ${NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}-rpc
spec:
  ports:
  - port: 9933
    name: http-rpc
  selector:
    app: ${NAME}
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None
