image: docker:stable


services:
  - docker:dind


variables:
  # CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  # DOCKER_HOST: tcp://docker:2375
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2


before_script:
  - test -z "$DOCKERIMAGE" && echo "DOCKERIMAGE must be defined" && exit 1
  - docker login -u $Docker_Hub_User_Parity -p $Docker_Hub_Pass_Parity
  - docker info

after_script:
  - docker logout





.build: &docker_build
  stage: build
  script:
    - cd $DOCKERFILE_DIR
      # - docker pull $CONTAINER_IMAGE:$CONTAINER_TAG || true
      # - docker build --cache-from $CONTAINER_IMAGE:$CONTAINER_TAG --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:$CONTAINER_TAG .
    - CONTAINER_DATE_TAG="$CONTAINER_TAG-$(date +%Y%m%d)"
    - docker build --tag $CONTAINER_IMAGE:$CONTAINER_DATE_TAG --tag $CONTAINER_IMAGE:$CONTAINER_TAG .
    - docker push $CONTAINER_IMAGE:$CONTAINER_DATE_TAG
    - docker push $CONTAINER_IMAGE:$CONTAINER_TAG
  only:
    refs:
      - schedules
      - web
    kubernetes: active
  tags:
    - kubernetes-parity-build



build:rust:nightly:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE: parity/rust
    CONTAINER_TAG:   nightly
    DOCKERFILE_DIR:  docker-files-for-Gitlab-CI-rust/rustup
  only:
    variables:
      - $DOCKERIMAGE == "parity/rust"


build:rust-android:gitlab-ci:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE: parity/rust-android
    CONTAINER_TAG:   gitlab-ci
    DOCKERFILE_DIR:  docker-files-for-Gitlab-CI-rust/cross/android
  only:
    variables:
      - $DOCKERIMAGE == "parity/rust-android"

build:substrate:nightly:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE: parity/substrate
    CONTAINER_TAG:   nightly
    DOCKERFILE_DIR:  docker-files-for-Gitlab-CI-rust/substrate
  only:
    variables:
      - $DOCKERIMAGE == "parity/substrate"

build:awscli:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE: parity/awscli
    CONTAINER_TAG:   latest
    DOCKERFILE_DIR:  awscli
  only:
    variables:
      - $DOCKERIMAGE == "parity/awscli"

build:tools:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE: parity/tools
    CONTAINER_TAG:   latest
    DOCKERFILE_DIR:  tools
  only:
    variables:
      - $DOCKERIMAGE == "parity/tools"



# special case as version tags are introduced
build:kubetools:
  <<: *docker_build
  variables:
    CONTAINER_IMAGE:         parity/kubetools
    CONTAINER_TAG:           latest
    DOCKERFILE_DIR:          kubectl-helm
    # https://github.com/kubernetes/kubernetes/releases
    KUBE_VERSION:            "1.13.4"
    # https://github.com/kubernetes/helm/releases
    HELM_VERSION:            "v2.13.1"
  only:
    variables:
      - $DOCKERIMAGE == "parity/kubetools"
  script:
    - cd $DOCKERFILE_DIR
    - docker build
      --build-arg VCS_REF="$(cut -c 1-7 refs/heads/master)"
      --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
      --build-arg KUBE_VERSION="${KUBE_VERSION}"
      --build-arg HELM_VERSION="${HELM_VERSION}"
      --tag $CONTAINER_IMAGE:$CONTAINER_TAG
      --tag $CONTAINER_IMAGE:$HELM_VERSION .
    - docker push $CONTAINER_IMAGE:$CONTAINER_TAG
    - docker push $CONTAINER_IMAGE:$HELM_VERSION





# vim: expandtab sts=2
